
import { Product, BusinessMetric, Order, Review } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    nameKey: 'premiumProduct1Name',
    descKey: 'premiumProduct1Desc',
    price: 70,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=400',
    category: 'oil',
    stock: 120
  },
  {
    id: 'p2',
    nameKey: 'premiumProduct2Name',
    descKey: 'premiumProduct2Desc',
    price: 1450,
    image: 'https://images.unsplash.com/photo-1543073351-7f98d172087d?auto=format&fit=crop&q=80&w=400',
    category: 'oil',
    stock: 8
  },
  {
    id: 'p3',
    nameKey: 'premiumProduct3Name',
    descKey: 'premiumProduct3Desc',
    price: 85,
    image: 'https://images.unsplash.com/photo-1541620028806-056774616223?auto=format&fit=crop&q=80&w=400',
    category: 'food',
    stock: 45
  }
];

export const MOCK_ORDERS: Order[] = [
  { id: 'ORD-001', customer: 'Ahmed Alami', total: 210, status: 'pending', date: '2023-10-24', items: '3x 1L Olive Oil' },
  { id: 'ORD-002', customer: 'Sarah Bensaid', total: 1450, status: 'shipped', date: '2023-10-23', items: '1x 5L Golden Tin' },
  { id: 'ORD-003', customer: 'Karim Idrissi', total: 85, status: 'delivered', date: '2023-10-22', items: '1x Spiced Olives' },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    userName: 'Layla M.',
    rating: 5,
    comment: 'The quality of the argan oil is unmatched. Truly authentic and reminds me of the Atlas Mountains.',
    date: '2023-11-10',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=200'
  },
  {
    id: 'r2',
    userName: 'Youssef H.',
    rating: 4,
    comment: 'Great olive oil, but the delivery took a bit longer than expected to Casablanca. Worth the wait though!',
    date: '2023-11-05'
  },
  {
    id: 'r3',
    userName: 'Emma S.',
    rating: 5,
    comment: 'I use this for my daily cooking. The taste is incredibly rich. Excellent branding too.',
    date: '2023-10-28'
  }
];

export const BUSINESS_METRICS: BusinessMetric[] = [
  { label: 'Total Revenue', value: '45,200 MAD', trend: '+12% this month' },
  { label: 'Active Leads', value: '128', trend: 'Via WhatsApp' },
  { label: 'Conversion Rate', value: '4.8%', trend: '+0.5% week' },
  { label: 'Retention', value: '62%', trend: 'Loyal base' }
];

export const TRANSLATIONS = {
  ar: {
    heroTitle: "إيزوران بيو: من عمق الجذور إلى باب دارك",
    heroSubtitle: "زيت زيتون طبيعي وحر",
    discoverProducts: "اكتشف المنتجات",
    premiumTitle: "منتجاتنا المميزة",
    addToCart: "أضف إلى السلة",
    buyNow: "اشتري الآن",
    checkoutWA: "إرسال الطلب عبر واتساب",
    cartTitle: "طلبيتي",
    emptyCart: "السلة فارغة حالياً",
    total: "المجموع الإجمالي",
    heritage: "تراثنا",
    contact: "تواصل معنا",
    managerPortal: "مركز القيادة",
    analytics: "الإحصائيات",
    pricing: "التسعير",
    orders: "الطلبيات",
    marketing: "التسويق",
    advisor: "الذكاء الاصطناعي",
    premiumProduct1Name: "زيت تراث العائلة",
    premiumProduct1Desc: "زيت زيتون بكر ممتاز، معصور على البارد. عبوة 1 لتر.",
    premiumProduct2Name: "العلبة الذهبية",
    premiumProduct2Desc: "عبوة عائلية اقتصادية. 5 لترات من زيت الزيتون البكر الممتاز.",
    premiumProduct3Name: "زيتون الجدة المتبل",
    premiumProduct3Desc: "وصفة تقليدية مع الليمون والأعشاب. عبوة زجاجية.",
    heritageMainHeading: "قصة عائلتنا مع زيت الزيتون",
    heritageDesc: "منذ أجيال، نزرع ونحصد ونعصر زيت الزيتون بكل حب وإخلاص. تراثنا يمتد عبر السنين، حاملين معنا قيم الأجداد ومبادئهم الراسخة في الجودة والصدق.",
    heritageVal1Title: "الالتزام والجدية",
    heritageVal1Desc: "نلتزم بمعايير عالية في كل خطوة من الإنتاج، من الشجرة إلى الزجاجة، لنقدم لكم منتجاً يستحق ثقتكم.",
    heritageVal2Title: "المصداقية والنزاهة",
    heritageVal2Desc: "الصدق والنزاهة في التعامل مع عملائنا وضمان جودة كل منتج، لأن صحتكم هي أثمن ما نملك.",
    heritageVal3Title: "الجودة العالية",
    heritageVal3Desc: "نختار أفضل الزيتون ونستخدم طرق العصر التقليدية للحفاظ على النكهة والفوائد الطبيعية.",
    imagePlaceholder: "صورة مزرعة الزيتون",
    brandPromiseHeadline: "رأسمالنا الحقيقي هو ثقتكم",
    brandPromiseSubheadline: "هدفنا ليس مجرد بيع الزيت، بل بناء علاقة دائمة أساسها المصداقية والشفافية.",
    brandPromiseBody: "نحن في إيزوران نؤمن أن الجودة لا تقبل المساومة. كل قطرة زيت هي عهد منا لكم بتقديم الأفضل، مباشرة من أشجارنا إلى مائدتكم. ثقتكم هي دافعنا للاستمرار في تقديم منتجات طبيعية 100%.",
    reviewsTitle: "آراء عملائنا",
    addReview: "أضف تقييمك",
    writeComment: "اكتب تعليقك هنا...",
    uploadPhoto: "إرفاق صورة",
    sendReview: "إرسال التقييم",
    justNow: "الآن",
    home: "الرئيسية",
    weight: "الوزن",
    quantity: "الكمية",
    share: "مشاركة عبر",
    back: "رجوع"
  },
  en: {
    heroTitle: "Izouran Bio: From Deep Roots to Your Door",
    heroSubtitle: "Natural and pure olive oil",
    discoverProducts: "Discover Products",
    premiumTitle: "Our Premium Products",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    checkoutWA: "Order via WhatsApp",
    cartTitle: "My Order",
    emptyCart: "Cart is currently empty",
    total: "Total Amount",
    heritage: "Our Heritage",
    contact: "Contact",
    managerPortal: "Command Center",
    analytics: "Analytics",
    pricing: "Pricing",
    orders: "Orders",
    marketing: "Marketing",
    advisor: "Intelligence",
    premiumProduct1Name: "Family Heritage Oil",
    premiumProduct1Desc: "Extra virgin olive oil, cold pressed. 1 liter.",
    premiumProduct2Name: "Golden Tin",
    premiumProduct2Desc: "Economic family pack. 5 liters of extra virgin oil.",
    premiumProduct3Name: "Grandma's Olives",
    premiumProduct3Desc: "Traditional recipe with lemon and herbs.",
    heritageMainHeading: "Our Family Story with Olive Oil",
    heritageDesc: "For generations, we have cultivated, harvested, and pressed olive oil with love and dedication. Our heritage spans years, carrying with us the ancestral values of quality and honesty.",
    heritageVal1Title: "Commitment & Seriousness",
    heritageVal1Desc: "We adhere to high standards at every stage of production, from tree to bottle, to provide you with a product worthy of your trust.",
    heritageVal2Title: "Credibility & Integrity",
    heritageVal2Desc: "Honesty in dealing with our customers and ensuring the quality of every product, because your health is our most precious asset.",
    heritageVal3Title: "High Quality",
    heritageVal3Desc: "We select the best olives and use traditional pressing methods to preserve flavor and natural benefits.",
    imagePlaceholder: "Olive Farm Image",
    brandPromiseHeadline: "Our True Capital is Your Trust",
    brandPromiseSubheadline: "Our goal isn't just selling oil, but building a lasting relationship based on credibility and transparency.",
    brandPromiseBody: "At Izouran, we believe that quality is non-negotiable. Every drop of oil is our pledge to provide the best, directly from our trees to your table. Your trust motivates us to continue offering 100% natural products.",
    reviewsTitle: "Customer Reviews",
    addReview: "Add a Review",
    writeComment: "Write your feedback here...",
    uploadPhoto: "Upload Photo",
    sendReview: "Send Review",
    justNow: "Just Now",
    home: "Home",
    weight: "Weight",
    quantity: "Quantity",
    share: "Share",
    back: "Back"
  },
  fr: {
    heroTitle: "Izouran Bio : Des racines à votre porte",
    heroSubtitle: "Huile d'olive naturelle et pure",
    discoverProducts: "Découvrir",
    premiumTitle: "Nos Produits Premium",
    addToCart: "Ajouter au panier",
    buyNow: "Acheter",
    checkoutWA: "Commander via WhatsApp",
    cartTitle: "Ma Commande",
    emptyCart: "Le panier est vide",
    total: "Total",
    heritage: "Notre Héritage",
    contact: "Contact",
    managerPortal: "Poste de Commande",
    analytics: "Statistiques",
    pricing: "Tarification",
    orders: "Commandes",
    marketing: "Marketing",
    advisor: "Intelligence",
    premiumProduct1Name: "Huile Patrimoine",
    premiumProduct1Desc: "Huile d'olive extra vierge, pression à froid. 1L.",
    premiumProduct2Name: "Bidon d'Or",
    premiumProduct2Desc: "Pack familial économique. 5L d'huile extra vierge.",
    premiumProduct3Name: "Olives de Grand-Mère",
    premiumProduct3Desc: "Recette traditionnelle au citron et herbes.",
    heritageMainHeading: "Notre Histoire Familiale",
    heritageDesc: "Depuis des générations, nous cultivons, récoltons et pressons l'huile d'olive avec amour. Notre héritage traverse les années, portant les valeurs de qualité et d'honnêteté de nos ancêtres.",
    heritageVal1Title: "Engagement & Sérieux",
    heritageVal1Desc: "Nous respectons des normes élevées à chaque étape, de l'arbre à la bouteille, pour vous offrir un produit digne de votre confiance.",
    heritageVal2Title: "Crédibilité & Intégrité",
    heritageVal2Desc: "Honnêteté envers nos clients et garantie de qualité, car votre santé est notre bien le plus précieux.",
    heritageVal3Title: "Haute Qualité",
    heritageVal3Desc: "Nous sélectionnons les meilleures olives et utilisons des méthodes traditionnelles pour préserver les saveurs et bienfaits.",
    imagePlaceholder: "Image de la Ferme d'Olives",
    brandPromiseHeadline: "Notre Véritable Capital est Votre Confiance",
    brandPromiseSubheadline: "Notre objectif n'est pas seulement de vendre de l'huile, mais de bâtir une relation durable basée sur la crédibilité et la transparence.",
    brandPromiseBody: "Chez Izouran, nous pensons que la qualité est non négociable. Chaque goutte d'huile est notre engagement à vous offrir le meilleur, directement de nos arbres à votre table. Votre confiance nous motive à continuer de proposer des produits 100% naturels.",
    reviewsTitle: "Avis Clients",
    addReview: "Ajouter un Avis",
    writeComment: "Écrivez votre commentaire ici...",
    uploadPhoto: "Ajouter une Photo",
    sendReview: "Envoyer l'Avis",
    justNow: "À l'instant",
    home: "Accueil",
    weight: "Poids",
    quantity: "Quantité",
    share: "Partager",
    back: "Retour"
  }
};
